name: master

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5' # The Go version to download (if necessary) and use.
      - name: Start up dependencies
        run: docker-compose up -d
      - name: Wait for dependencies to start up
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Master buld tests
        run: sudo go test ./... -v
